Release version 1.0.0
glotzerlab/synced_collections pull request #8
Opened 2023-05-10 04:33 UTC by vyasr

## Description

Version 1.0 major release

## Checklist:

- [x] I agree with the terms of the [Contributor Agreement](https://github.com/glotzerlab/synced_collections/blob/main/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/synced_collections/blob/main/contributors.yaml).
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/synced_collections/blob/main/changelog.txt) and added any related issue and pull request numbers for future reference.

2023-05-10 05:18 UTC, vyasr commented
More information on the changes to the publish workflow's authentication, see https://docs.pypi.org/trusted-publishers/.

2023-05-10 05:37 UTC, vyasr commented
Would also recommend that reviewers have a look at https://github.com/glotzerlab/synced_collections/pull/7, which sets up automated Github Releases. I merged that quickly so that I could verify that the deployment workflows for PyPI (or at least TestPyPI) worked correctly in this PR, but I am happy to edit the workflow as well in this PR.

2023-05-10 13:05 UTC, bdice requested changes
Blocking on this until some issues in #7 are addressed. I wish I could have reviewed that PR before merge... but I'll leave some comments and file a follow-up there.

2023-05-10 13:48 UTC, bdice commented
Opened #9. I'd like to merge that before this PR is merged.

2023-05-13 19:07 UTC, vyasr commented
> Opened #9. I'd like to merge that before this PR is merged.

Thanks @bdice! Your PR is merged now. Let me know if you'd like to see anything else. No rush, I would like at least one more approval before I merge this PR in any case.

2023-05-17 14:52 UTC, bdice approved these changes
With #9 merged, I approve this.

2023-05-17 14:54 UTC, bdice requested changes
@vyasr I thought some more and think I want to block on this. Before we release 1.0.0 here, it might be good to try the packaging in practice. I'll create a test branch in signac that installs this from git and removes the existing `synced_collection` code.

2023-05-17 15:20 UTC, bdice commented
I opened these PRs. Looks like things are passing against the `main` branch here, so we can merge this PR and release 1.0.0 before or after merging the downstream PRs.
- https://github.com/glotzerlab/signac/pull/924
- https://github.com/glotzerlab/signac-docs/pull/189

2023-05-17 15:21 UTC, bdice approved these changes

2023-05-17 15:42 UTC, b-butler commented on changelog.txt
> +[1.0.0] -- 2023-05-10
Will need to be modified

2023-05-17 15:43 UTC, b-butler approved these changes
I am happy with this. We just need to change the release date.

2023-05-17 16:36 UTC, vyasr commented on changelog.txt
> +[1.0.0] -- 2023-05-10
```suggestion
[1.0.0] -- 2023-05-17
```

2023-05-17 16:49 UTC, merged